### ISSUE TITLE
librsvg-CRITICAL on results page (Docker)

### ISSUE THREAD

**Issue by Dominion0815** [e7d/speedtest#57]
Hi,

I get these errors when I try to share a link or am on the results page.

Version:
latest docker image

My docker-compose.yml config:
```
version: '3'

services:
  speedtest:
    image: e7db/speedtest:latest
    restart: always
    ports:
      - "8083:80"
    volumes:
      - ./results:/app/results
```

Error message in console:
`GET http://x.x.x.x:8083/results/Command failed: (process:19): librsvg-CRITICAL **: 11:01:58.950: Handle could not read or parse the SVG; did you check for errors during the loading stage.json`

```
Uncaught DOMException: Document.querySelectorAll: 'circle[result-id="Command failed: 
(process:19): librsvg-CRITICAL **: 11:01:58.950: Handle could not read or parse the SVG; did you check for errors during the loading stage?

(process:19): librsvg-CRITICAL **: 11:01:58.951: Handle could not read or parse the SVG; did you check for errors during the loading stage?
convert: negative or zero image size `/app/results/72da8075-091e-472e-91b3-d6589ebbf571.svg' @ error/image.c/SetImageExtent/2661.
convert: no decode delegate for this image format `/app/results/72da8075-091e-472e-91b3-d6589ebbf571.svg' @ error/svg.c/ReadSVGImage/3401.
convert: no images defined `/app/results/72da8075-091e-472e-91b3-d6589ebbf571.png' @ error/convert.c/ConvertImageCommand/3273.
"]' is not a valid selector app.cbb9b66b.js:1
    toggleCirclesFocus http://x.x.x.x:8083/app.cbb9b66b.js:1
    printTable http://x.x.x.x:8083/app.cbb9b66b.js:1
```

Best regards
Dominion
